services:
  vnspickletrack-app:
    container_name: vnspickletrack-prototype
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map cổng 8080 của máy bạn vào cổng 80 trong container
    restart: unless-stopped # Tự khởi động lại nếu bị crash hoặc restart máy chủ
