@Vns.PickleTrack.Api_HostAddress = http://localhost:5081

GET {{Vns.PickleTrack.Api_HostAddress}}/health/live
Accept: application/json

###

GET {{Vns.PickleTrack.Api_HostAddress}}/api/v1/system/info
Accept: application/json

###

GET {{Vns.PickleTrack.Api_HostAddress}}/api/v1/system/database
Accept: application/json

###
